version: '3.1'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    command: ['yarn', 'start:dev', 'gateway']
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./apps/gateway/.env

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: ['yarn', 'start:dev', 'auth']
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app

    depends_on:
      - mongo
    env_file:
      - ./apps/auth/.env

  event:
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
    command: ['yarn', 'start:dev', 'event']
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app

    depends_on:
      - mongo
    env_file:
      - ./apps/event/.env

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=maple
