version: '3.1'

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: ['yarn', 'start:dev', 'auth']
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/auth/.env

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=maple
